version: "3.4"
services:
  vite_test:
    container_name: vite_test
    image: node:lts
    working_dir: /var/www/html/app/
    ports:
      - "3000:3000"
    volumes:
      - ./app/:/var/www/html/app
    entrypoint: ["bash", "-c", "npm ci && npm run dev"]
